<link rel="stylesheet" type="text/css" href="css/proto.css" title="Default">
<link rel="stylesheet" type="text/css" media="print" href="css/print.css">
<link rel="stylesheet" type="text/css" href="css/media-query.css">

</head>
<body>
  <div id="container">
    <header>
      <!-- Google Search -->
      <section id="search">
        <form method="get" action="http://www.google.com/search"> 
			<input type="text" name="q" value="">
			<input type="hidden" name="sitesearch" value="www.thenet.ca">
			<input type="submit" value="Search">
		</form>
       </section>
       <!-- Google Search -->