<footer id="mainfooter">
	<nav class="footernav">
	<p>COMP 1950 Project Designed by <a href="index.shtml"><strong><em>WebBusters</em></strong></a> - Copyright &copy; 2013</p>
	<p>All Rights Reserved</p>
		<ul>
			<li><a href="sitemap.shtml">[Sitemap]</a></li>
			<li><a href="http://validator.w3.org/check?uri=referer">[Validate HTML]</a></li>
			<li><a href="http://jigsaw.w3.org/css-validator/check/referer">[Validate CSS]</a></li>
		</ul>
	</nav>
</footer>
