<!-- START top-most INCLUDE -->

<!DOCTYPE html>
<html>
<head>
	<title>Mummy's Home Real Estate Listings</title>
	<meta charset="utf-8">
	<meta name="description" content="Mummy's Home Real Estate Listing website">
	
	<!-- CSS Reset from HTML5Doctor, http://html5resetcss.googlecode.com/files/html5reset-1.6.1.css -->
	<link rel="stylesheet" type="text/css" href="html5reset-1.6.1.css">
	
	<!-- Main stylesheet -->
	<link rel="stylesheet" type="text/css" href="week5_main.css" media="screen" title="Main Stylesheet">
	<!-- Alternate stylesheet -->
	<link rel="alternate stylesheet" type="text/css" href="week5_alternate.css" media="screen" title="Alternate Stylesheet">
	<!-- Print stylesheet -->
	<link rel="stylesheet" type="text/css" href="week5_print.css" media="print">

	
	<!-- Image hover changer -->
	<script type="text/javascript">
	<!--
		function swapImage(img, cap){
			document.getElementById("primaryImg").src = "images/" + img;
			document.getElementById("primaryCap").innerHTML = cap;
		}
	// -->
	</script>
	
	<!-- Javascript style switcher -->
	<script type="text/javascript" src="styleswitcher.js"></script>
	
	
	<!-- GOOGLE ANALYTICS -->
	<script type="text/javascript">
	var _gaq = _gaq || [];
	_gaq.push(['_setAccount', 'UA-37799767-5']);
	_gaq.push(['_trackPageview']);
	(
		function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		}
	)();
	</script>
	<!-- GOOGLE ANALYTICS END -->

	
</head>
<body>
	<header>
		<hgroup>
			<h1>Mummy's Home</h1>
			<h2>Real Estate Listings</h2>
		</hgroup>
	</header>
	
<!-- END top_most INCLUDE -->