<!-- START gallery INCLUDE -->


	<div id="secondary_image">
		<figure>
			<a href="index.shtml?pyramids"><img src="images/pyramids.jpg" alt="Pyramids from outside"></a>
			<figcaption>Pyramids from outside</figcaption>
		</figure>
		<figure>
			<a href="index.shtml?interior"><img src="images/interior.jpg" alt="Interior cooridor"></a>
			<figcaption>Interior cooridor</figcaption>
		</figure>
		<figure>
			<a href="index.shtml?interior2"><img src="images/interior2.jpg" alt="Heiroglyphics and sculptures"></a>
			<figcaption>Hieroglyphics and sculptures</figcaption>
		</figure>
		<figure>
			<a href="index.shtml?chambers"><img src="images/chambers.png" alt="King's, Queen's, and unfinished chambers"></a>
			<figcaption>King's, Queen's, and unfinished chambers</figcaption>
		</figure>
		<figure>
			<a href="index.shtml?sunset"><img src="images/sunset.jpg" alt="Pyramids at sunset"></a>
			<figcaption>Pyramids at sunset</figcaption>
		</figure>
		<figure>
			<a href="index.shtml?interior_plan"><img src="images/interior_plan.jpg" alt="Interior layout"></a>
			<figcaption>Interior layout</figcaption>
		</figure>
		<figure>
			<a href="index.shtml?pyramid_math"><img src="images/pyramid_math.jpg" alt="Amazing Pyramid math!"></a>
			<figcaption>Amazing Pyramid math!</figcaption>
		</figure>
	</div>
</section> <!-- end IMAGES -->

<!-- END gallery INCLUDE -->