<nav>
	<ul>
		<li><a href="http://students.thenet.ca/nyuen">Home</a></li>
		<li><a href="http://www.bcit.ca">BCIT</a></li>
		<li><a href="http://my.bcit.ca">My.Bcit.Ca</a></li>
		<li><a href="http://mls.ca">MLS Listings</a></li>
		<li><a href="http://realtylink.org/">RealtyLinkOnline</a></li>
		<li id="style_switcher">CSS Switcher
			<ul>
				<li><a href="#" onClick="setActiveStyleSheet('Main Stylesheet'); return false;">Main Style</a></li>
				<li><a href="#" onclick="setActiveStyleSheet('Alternate Stylesheet'); return false;">Alternate Style</a></li>
			</ul>
		</li>
	</ul>
</nav>