<!-- START bottom-most INCLUDE -->

<section id="disclaimer">
			<p>All information displayed is believed to be accurate but is not guaranteed and should be independently verified. No warranties or representations are made of any kind. All photos were borrowed from the internet (which I PROMISE to delete when this course is done!) and information was researched on Wikipedia. PLEASE do not try to contact Mr. Morsi about this listing!</p>
		</section>
		
	</section> <!-- end CONTAINER -->
	
<!--******************** FOOTER **********************-->
	<footer>
		<p>Copyright &copy; 2013</p>
		<a href="http://validator.w3.org/check?uri=http%3A%2F%2Fstudents.thenet.ca%2Fnyuen%2Fweek%2F6%2FSSI%2Findex.shtml">Validate HTML5</a>
		<a href="http://jigsaw.w3.org/css-validator/check/referer">Validate CSS</a>
	</footer>
</body>
</html>

<!-- END bottom-most INCLUDE -->