<!-- START gallery INCLUDE -->


<section id="images">
				
	<div id="gallery">
		<p>Click on an image to enlarge it.</p>
		<figure>
			<a href="images/pyramids.jpg" title="Pyramids from outside"><img src="images/pyramids.jpg" alt="Pyramids from outside"></a>
		</figure>
		<figure>
			<a href="images/interior.jpg" title="Interior cooridor"><img src="images/interior.jpg"  alt="Interior cooridor"></a>
		</figure>
		<figure>
			<a href="images/interior2.jpg" title="Heiroglyphics and sculptures"><img src="images/interior2.jpg" alt="Heiroglyphics and sculptures"></a>
		</figure>
		<figure>
			<a href="images/chambers.png" title="King's, Queen's, and unfinished chambers"><img src="images/chambers.png" alt="King's, Queen's, and unfinished chambers"></a>
		</figure>
		<figure>
			<a href="images/sunset_small.jpg" title="Pyramids at sunset"><img src="images/sunset_small.jpg" alt="Pyramids at sunset"></a>
		</figure>
		<figure>
			<a href="images/interior_plan.jpg" title="Interior layout"><img src="images/interior_plan.jpg" alt="Interior layout"></a>
		</figure>
		<figure>
			<a href="images/pyramid_math_small.jpg" title="Amazing Pyramid math!"><img src="images/pyramid_math_small.jpg" alt="Amazing Pyramid math!"></a>
		</figure>
		<figure>
			<a href="images/night.jpg" title="Pyramids at night"><img src="images/night.jpg" alt="Pyramids at night"></a>
		</figure>
		
		<script type="text/javascript">
		$(document).ready(function(){
			$("#gallery a").lightBox({
				imageLoading: 'lightbox/images/lightbox-ico-loading.gif',
				imageBtnClose: 'lightbox/images/lightbox-btn-close.gif',
				imageBtnPrev: 'lightbox/images/lightbox-btn-prev.gif',
				imageBtnNext: 'lightbox/images/lightbox-btn-next.gif',
				shrinkToFit: true
			});
		});
		</script>
	</div>
</section> <!-- end IMAGES -->

<!-- END gallery INCLUDE -->